language: java

matrix:
  include:
    - os: linux
      jdk: openjdk11
    - os: osx
      osx_image: xcode9.3

cache:
  directories:
  - $HOME/.m2
  before_cache:
  - rm -rf $HOME/.m2/repository/org/messaginghub/*

script:
  - mvn clean test jacoco:report

after_success:
  - bash <(curl -s https://codecov.io/bash)
